go_binary(
    name = "please_js",
    srcs = ["main.go"],
    deps = [
        "//third_party/go:go-flags",
        "//tools/please_js/bundle",
        "//tools/please_js/resolve",
        "//tools/please_js/transpile",
    ],
    visibility = ["PUBLIC"],
)
