go_library(
    name = "common",
    srcs = ["common.go", "env.go", "package_json.go"],
    deps = [
        "//third_party/go:esbuild_api",
    ],
    visibility = ["//tools/please_js/...", "//test/prebundle_plugins/..."],
)
