plugin_repo(
    name = "go",
    revision = "v1.28.2",
)

plugin_repo(
    name = "js",
    plugin = "js-rules",
    owner = "becomeliminal",
    revision = "a266bbf4aee699018e647c2b50740149a7d7a1f3",
)
