plugin_repo(
    name = "go",
    revision = "v1.28.2",
)

plugin_repo(
    name = "js",
    plugin = "js-rules",
    owner = "becomeliminal",
    revision = "69935c6",
)
plugin_repo(
  name = "shell",
  revision = "v0.2.1",
  plugin = "shell-rules",
  owner = "please-build",
)
