subinclude("//build_defs:js")

js_library(
    name = "components",
    srcs = [
        "index.ts",
        "App.tsx",
        "Counter.tsx",
        "Greeting.tsx",
    ],
    deps = ["//third_party/js:react"],
    visibility = ["//test/react/..."],
)
