go_library(
    name = "esmdev",
    srcs = ["esmdev.go"],
    deps = [
        "//third_party/go:esbuild_api",
        "//tools/please_js/common",
    ],
    visibility = ["//tools/please_js/..."],
)
