subinclude("//build_defs:js")

js_library(
    name = "ui",
    srcs = ["Counter.tsx"],
    module_name = "test/common/ui",
    deps = [
        "//third_party/js:react",
    ],
    visibility = ["//test/..."],
)
