subinclude("//build_defs:js")

js_test(
    name = "asset_test",
    srcs = [
        "asset_test.js",
        "fixtures/image.png",
        "fixtures/image.svg",
        "fixtures/image.jpg",
        "fixtures/image.gif",
        "fixtures/image.webp",
        "fixtures/font.woff2",
        "fixtures/font.ttf",
        "fixtures/audio.mp3",
    ],
)
