subinclude("//build_defs:npm")

npm_repo(
    name = "ms_2.1.2",
    hashes = ["1157a6e30d3ffe1b9fcaf3a39caf159f8dc981199a3380c78ddd89f73bcefb48"],
    pkg = "ms",
    version = "2.1.2",
)

npm_repo(
    name = "ms_2.1.3",
    hashes = ["f6616e15e530ed552f9daa2d3ce71963947c6bc7c98c9b64fd3e673fd02622c6"],
    pkg = "ms",
    version = "2.1.3",
)

filegroup(
    name = "lockfile",
    srcs = ["pnpm-lock.yaml"],
    visibility = ["PUBLIC"],
)
