subinclude("//build_defs:js")

js_binary(
    name = "minify",
    entry_point = "main.js",
    format = "cjs",
    platform = "node",
    minify = True,
)

js_binary(
    name = "no_minify",
    entry_point = "main.js",
    format = "cjs",
    platform = "node",
)
