package junit

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// EditorConfig builds the tsconfig fragment that lets an editor's language
// server resolve what the build system provides.
//
// The TypeScript server resolves an import by walking node_modules up from the
// file, and this repo deliberately has no node_modules in its source tree --
// so on a fresh checkout the editor knows nothing. rust-rules answers the same
// problem for rust-analyzer with rust_project: discover everything from the
// graph, write one file at the root, keep no list by hand. This is that
// pattern with tsconfig "paths" as the vocabulary.
//
// First-party packages map to their sources -- the files being edited, the
// same identity the dev server serves -- and a trailing "*" fallback maps
// everything else into the built trees, where the fetched packages and their
// type declarations live.
//
// Input lines, from the generating script:
//
//	lib	<package>	<srcDir>
//	tree	<path-under-repo>
func EditorConfig(lines []string) (string, error) {
	paths := map[string][]string{}
	var trees []string
	for _, line := range lines {
		fields := strings.Split(strings.TrimSpace(line), "\t")
		switch {
		case line == "":
		case fields[0] == "lib" && len(fields) == 3:
			pkg, srcDir := fields[1], fields[2]
			// Both entry spellings, because paths arrays are fallbacks and
			// the label does not carry which one the library uses.
			// ./-relative, resolved against the config file at the repo root.
			// TypeScript 7 removed baseUrl and refuses bare relative entries,
			// found by running the generated file through the real compiler.
			paths[pkg] = []string{"./" + srcDir + "/index.ts", "./" + srcDir + "/index.tsx", "./" + srcDir + "/index.js"}
			paths[pkg+"/*"] = []string{"./" + srcDir + "/*"}
		case fields[0] == "tree" && len(fields) == 2:
			// The npm_link output IS the tree root -- appending node_modules
			// here was the doubled-path bug the first real run printed.
			trees = append(trees, "./"+fields[1]+"/*")
		default:
			return "", fmt.Errorf("unrecognised line %q; expected lib<TAB>pkg<TAB>srcDir or tree<TAB>path", line)
		}
	}
	if len(trees) > 0 {
		sort.Strings(trees)
		paths["*"] = trees
	}

	keys := make([]string, 0, len(paths))
	for k := range paths {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	ordered := make(map[string][]string, len(paths))
	for _, k := range keys {
		ordered[k] = paths[k]
	}

	out, err := json.MarshalIndent(map[string]any{
		"//": "Generated by `plz run` of a js_project target; do not edit. " +
			"Extend this from the repo tsconfig so the editor resolves what the build provides.",
		"compilerOptions": map[string]any{
			"paths": ordered,
		},
	}, "", "  ")
	if err != nil {
		return "", err
	}
	return string(out) + "\n", nil
}
