go_library(
    name = "resolve",
    srcs = glob(["*.go"]),
    deps = [
        "//third_party/go:buildtools",
        "//tools/please_js/common",
    ],
    visibility = ["//tools/please_js/..."],
)
