subinclude("//build_defs:js")

js_library(
    name = "fake_pkg",
    module_name = "fake-pkg",
    srcs = [
        "package.json",
        "index.js",
        "browser.js",
    ],
    visibility = ["//test/browser_field/..."],
)
